---

- name: Get OpenShift ingress certificate secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ ocp4_workload_ai_summit2025_openshift_ingress_secret_certs }}"
    namespace: openshift-ingress
  register: r_secret_ingress_cert
  retries: 120
  delay: 10
  ignore_errors: true
  until:
    - r_secret_ingress_cert is defined
    - r_secret_ingress_cert.resources is defined
    - r_secret_ingress_cert.resources | length > 0
    - r_secret_ingress_cert.resources[0] is defined
    - r_secret_ingress_cert.resources[0].data is defined

- name: Get OpenShift ingress certificate and private key"
  ansible.builtin.set_fact:
    ocp4_workload_ai_summit2025_openshift_ingress_cert: "{{ r_secret_ingress_cert | json_query('resources[0].data.\"tls.crt\"') }}"
    ocp4_workload_ai_summit2025_openshift_ingress_key: "{{ r_secret_ingress_cert | json_query('resources[0].data.\"tls.key\"') }}"

- name: Create AMQ Streams application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'amq-streams/amq-streams-application.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 60
  ignore_errors: true
  register: amq_streams_result
  until: amq_streams_result is not failed

- name: Print result from the previous task
  ansible.builtin.debug:
    var: amq_streams_result

- name: Wait for AMQ Streams subscriptions to be created
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: amq-streams-operator
    namespace: openshift-operators
  register: r_amq_subscription
  retries: 30
  delay: 10
  until:
    - r_amq_subscription.resources is defined
    - r_amq_subscription.resources | length > 0

- name: Wait for AMQ Streams InstallPlan to be created
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: openshift-operators
  register: r_install_plans
  vars:
    _query: >-
      [?contains(spec.clusterServiceVersionNames[] | join(',', @), 'amqstreams')]
  retries: 60
  delay: 10
  until:
    - r_install_plans.resources | default([]) | length > 0
    - r_install_plans.resources | to_json | from_json | json_query(_query)

- name: Get AMQ Streams InstallPlan name
  ansible.builtin.set_fact:
    amq_streams_install_plan_name: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?contains(spec.clusterServiceVersionNames[] | join(',', @), 'amqstreams')].metadata.name|[0]

- name: Print AMQ Streams InstallPlan name
  ansible.builtin.debug:
    msg: "AMQ Streams InstallPlan: {{ amq_streams_install_plan_name }}"

- name: Get AMQ Streams InstallPlan details
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ amq_streams_install_plan_name }}"
    namespace: openshift-operators
  register: r_install_plan

- name: Approve AMQ Streams InstallPlan if necessary
  when:
    - r_install_plan.resources | length > 0
    - r_install_plan.resources[0].status.phase is match("RequiresApproval")
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      metadata:
        name: "{{ amq_streams_install_plan_name }}"
        namespace: openshift-operators
      spec:
        approved: true

- name: Wait for AMQ Streams operators to be installed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ item }}"
    namespace: openshift-operators
  register: r_csv
  retries: 60
  delay: 10
  until:
    - r_csv.resources is defined
    - r_csv.resources | length > 0
    - r_csv.resources[0].status.phase is defined
    - r_csv.resources[0].status.phase == "Succeeded"
  loop:
    - amqstreams.v3.1.0-7
    - amq-streams-console.v2.9.3-7
  ignore_errors: true

- name: Print AMQ Streams operator installation status
  ansible.builtin.debug:
    msg: "AMQ Streams operators installed successfully"
